//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHShows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema_T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cinema_T()
        {
            this.ShowTime_T = new HashSet<ShowTime_T>();
        }
    
        public int CinemaID { get; set; }
        public string Name { get; set; }
        public int CityID { get; set; }
        public int CountryID { get; set; }
        public string Location { get; set; }
        public string LatLong { get; set; }
    
        public virtual City_T City_T { get; set; }
        public virtual Country_T Country_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowTime_T> ShowTime_T { get; set; }
    }
}
