//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHShows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies_T
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies_T()
        {
            this.Media_T = new HashSet<Media_T>();
            this.ShowTime_T = new HashSet<ShowTime_T>();
        }
    
        public int MovieID { get; set; }
        public string Name { get; set; }
        public string Rated { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> ReleasedOn { get; set; }
        public string Stars { get; set; }
        public string Directors { get; set; }
        public string Writers { get; set; }
        public string Details { get; set; }
        public int LanguageID { get; set; }
        public string YoutubeURL { get; set; }
    
        public virtual Language_T Language_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Media_T> Media_T { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowTime_T> ShowTime_T { get; set; }
    }
}
