//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHShows.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowTime_T
    {
        public int ShowtimeID { get; set; }
        public string ShowTime { get; set; }
        public Nullable<int> CinemaID { get; set; }
        public Nullable<int> MovieID { get; set; }
    
        public virtual Cinema_T Cinema_T { get; set; }
        public virtual Movies_T Movies_T { get; set; }
    }
}
